# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c27ca8b610aedc1465dbf71c65683c8978fec04242f900054cd81c97891972cfd663e2b224f2705073b8f889ea467715f3f9a05acd1651ad5981b761d4dd3d3a

test:
  secret_key_base: b13a6f49524b3eeec27771aa5755fd6916c8067b2cf426d871fe85f407dd3ca290fb31a85aa1aa86abe188bd2b61f3d26dd0c84b74313fae0b9711f85175c86b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
